### ISSUE TITLE
If you manually deploy the app you need to make sure the dash service name includes "dashDB" in the name

### ISSUE THREAD

**Issue by johnnason** [ibm-watson-data-lab/pipes#24]
I wanted to use custom service names, and I named my dashDB instance "dash-metrics-warehouse".
The pipes code fails in this scenario.

2015-08-11T16:47:51.62-0400 [App/0]      OUT     at dashDBConnection.getService (/home/vcap/app/server/dw/connection.js:39:10)
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at dashDBConnection.getConnectionDetails (/home/vcap/app/server/dw/dashDBConnection.js:39:22)
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at dataworks.createActivity (/home/vcap/app/server/dw/dataworks.js:212:55)
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at /home/vcap/app/server/run/cloudantToDashActivitiesStep.js:112:17
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at iterate (/home/vcap/app/node_modules/async/lib/async.js:265:13)
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at async.forEachOfSeries.async.eachOfSeries (/home/vcap/app/node_modules/async/lib/async.js:284:9)
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at /home/vcap/app/server/run/cloudantToDashActivitiesStep.js:61:4
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at Request._callback (/home/vcap/app/server/dw/dataworks.js:133:11)
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at Request.self.callback (/home/vcap/app/node_modules/request/request.js:197:22)
2015-08-11T16:47:51.62-0400 [App/0]      OUT     at Request.emit (events.js:110:17)

It is hard-coded to look for "dashdb" in the service name.

**Comment by lornajane** [comment]
Thanks for the bug report!  In case it wasn't already obvious, this repo is no longer supported.  I'm closing this issue to make clear that it won't be attended to.
